### ISSUE TITLE
mason-0.2.5 fails to build with ghc-9.4.3 in Stackage Nightly

### ISSUE THREAD

**Issue by juhp** [fumieval/mason#10]
```
Building library for mason-0.2.5..                                                                                                  
[1 of 4] Compiling Mason.Builder.Internal                                                                                           
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/mason-0.2.5-4eda0ef67a4f4475f8ab1dc38aca2a86ff5a522eab57e7c63ddc66b4da9bd874/src/Mason/Builde
r/Internal.hs:497:48: error:                                                                                                        
    • Couldn't match expected type ‘GHC.Word.Word16’       
                  with actual type ‘Word8’                        
    • In the first argument of ‘U16.chr2’, namely ‘w’
      In the second argument of ‘($)’, namely
        ‘U16.chr2 w (A.unsafeIndex arr (i + 1))’                                                                                    
      In the expression: ord $ U16.chr2 w (A.unsafeIndex arr (i + 1))
    |                                                                                                                               
497 |                         let c = ord $ U16.chr2 w (A.unsafeIndex arr (i+1))         
    |                                                ^                                                                              
                                                                                                                                    
/var/stackage/work/unpack-dir/unpacked/mason-0.2.5-4eda0ef67a4f4475f8ab1dc38aca2a86ff5a522eab57e7c63ddc66b4da9bd874/src/Mason/Builde
r/Internal.hs:497:51: error:                                                                                                        
    • Couldn't match expected type ‘GHC.Word.Word16’             
                  with actual type ‘Word8’                                                                                          
    • In the second argument of ‘U16.chr2’, namely                                                                                  
        ‘(A.unsafeIndex arr (i + 1))’                                                                                               
      In the second argument of ‘($)’, namely                                                                                       
        ‘U16.chr2 w (A.unsafeIndex arr (i + 1))’      
      In the expression: ord $ U16.chr2 w (A.unsafeIndex arr (i + 1))                                                               
    |                   
497 |                         let c = ord $ U16.chr2 w (A.unsafeIndex arr (i+1))                                                    
    |                                                   ^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by dminuoso** [comment]
Should be fixed in https://github.com/fumieval/mason/pull/9
